version: '3'
services:
  app:
    container_name: app
    environment:
      - MYSQL_DATABASE
      - DB_HOST
      - MYSQL_USER
      - MYSQL_PASSWORD
    ports:
      - 80:4200
    depends_on:
      - database
    build: .
    # 1. This should allow for nodemon but isnt working!
    # 2. The server will reload on-save with -L flag, but does not load changes.
    volumes:   
     - .:/usr/src/app/docker-express-mysql
  database:
    container_name: database
    environment:
      - MYSQL_DATABASE
      - MYSQL_RANDOM_ROOT_PASSWORD
      - MYSQL_USER
      - MYSQL_PASSWORD
    ports:
      - 3306
    image: mysql
    volumes:
      - db-store:/var/lib/mysql
volumes:
  db-store: