version: '3'
services:
  app:
    container_name: user-template
    environment:
      - MYSQL_DATABASE
      - DB_HOST
      - MYSQL_USER
      - MYSQL_PASSWORD
      - JWT_SECRET
    ports:
      - 80:4200
    depends_on:
      - database
    build: .
  database:
    container_name: user-template-database
    environment:
      - MYSQL_DATABASE
      - MYSQL_RANDOM_ROOT_PASSWORD
      - MYSQL_USER
      - MYSQL_PASSWORD
    ports:
      - 3306
    image: mysql
    volumes:
      - user-dbstore:/var/lib/mysql
volumes:
  user-dbstore: