version: '3'
services:
  app:
    build: .
    depends_on:
      - db
    environment:
      - DB_DATABASE=data
      - DB_HOST=db
      - MYSQL_USER=app
      - MYSQL_PASSWORD=1%ranSTring!k6i4hdu322o
    ports:
      - 80:4200
    restart: always
  db:
    image: mysql
    environment:
      - MYSQL_DATABASE=data
      - MYSQL_RANDOM_ROOT_PASSWORD=forsure
      - MYSQL_USER=app
      - MYSQL_PASSWORD=1%ranSTring!k6i4hdu322o
    ports:
      - 3306
    restart: always
    volumes:
      - db_persistent:/var/lib/mysql
volumes:
  db_persistent: {}