version: '3'
services:
  app:
    build: .
    depends_on:
      - db
    environment:
      - MYSQL_DATABASE
      - DB_HOST
      - MYSQL_USER
      - MYSQL_PASSWORD
    ports:
      - 80:4200
    restart: always
  db:
    image: mysql
    environment:
      - MYSQL_DATABASE
      - MYSQL_RANDOM_ROOT_PASSWORD
      - MYSQL_USER
      - MYSQL_PASSWORD
    ports:
      - 3306
    restart: always
    volumes:
      - db_persistent:/var/lib/mysql
volumes:
  db_persistent: {}